### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by byroot96**
thanks for @yasserbdj96 @byroot96 @ressayb

### CODE REVIEW

**Comment by yasserbdj96** [comment]
thanks to @byroot96 @yasserbdj96 @ressayb

**Review by yasserbdj96 — APPROVED** [review]
@byroot96 @yasserbdj96 @ressayb

**Comment by ressayb** [comment]
@byroot96 @yasserbdj96 @ressayb

**Review by ressayb — APPROVED** [review]
@byroot96 @yasserbdj96 @ressayb

**Pull request merged**
